#pragma once
#include <Inspection/IInspectionConfiguration.h>
#include <Inspection/IInspectionConfigurationCollection.h>
#include <Inspection/IAcquisitionUnitConfiguration.h>
#include <Inspection/IAcquisitionUnitConfigurationCollection.h>
#include <Inspection/IAngleRange.h>
#include <Inspection/ICapabilitiesConfiguration.h>
#include <Inspection/IConventionalBeam.h>
#include <Inspection/IConventionalConfiguration.h>
#include <Inspection/IDigitizerTechnologyConfiguration.h>
#include <Inspection/IEncoderConfiguration.h>
#include <Inspection/IEncoderConfigurationCollection.h>
#include <Inspection/IFocusing.h>
#include <Inspection/IFormation.h>
#include <Inspection/IFormationCompound.h>
#include <Inspection/IFormationLinear.h>
#include <Inspection/IFormationSectorial.h>
#include <Inspection/IFormationCustom.h>
#include <Inspection/IGateConfiguration.h>
#include <Inspection/IGateConfigurationCollection.h>
#include <Inspection/IGateConfigurationFunction.h>
#include <Inspection/IConfiguration.h>
#include <Inspection/IConfigurationCollection.h>
#include <Inspection/IInspectionMethod.h>
#include <Inspection/IInspectionMethodCollection.h>
#include <Inspection/IInspectionMethodConventional.h>
#include <Inspection/IInspectionMethodFactory.h>
#include <Inspection/IInspectionMethodPhasedArray.h>
#include <Inspection/IInspectionMethodPulseEcho.h>
#include <Inspection/IInspectionMethodTofd.h>
#include <Inspection/IInspectionMethodPitchCatch.h>
#include <Inspection/IInspectionMethodTotalFocusing.h>
#include <Inspection/IPhasedArrayBeamSet.h>
#include <Inspection/IPhasedArrayBeamConfiguration.h>
#include <Inspection/IPhasedArrayConfiguration.h>
#include <Inspection/ITotalFocusingMethodConfiguration.h>
#include <Inspection/ITransformation2D.h>
#include <Inspection/IUltrasoundDigitizerConfiguration.h>
#include "Inspection/IDigitalInputPinConfiguration.h"
#include <Inspection/ICalibrationStates.h>
#include <Inspection/IWaveTypeCollection.h>
#include <Inspection/IFocusingZone.h>
#include <Inspection/IFocusingLimits.h>
#include <Inspection/IIdentifierCollection.h>
#include <Inspection/IFullMatrixCaptureConfiguration.h>
#include <Inspection/IFullMatrixCaptureConfigurationCollection.h>
#include <Inspection/IThicknessSettings.h>
#include <Inspection/IThicknessSource.h>
#include <Inspection/IThicknessGate.h>
