#pragma once
#include <PartDefinition/IAxis.h>
#include <PartDefinition/IBarGeometry.h>
#include <PartDefinition/ICylinderSurface.h>
#include <PartDefinition/IGeometry.h>
#include <PartDefinition/IMappingUV.h>
#include <PartDefinition/IMaterial.h>
#include <PartDefinition/IPatch.h>
#include <PartDefinition/IPatchCollection.h>
#include <PartDefinition/IPipeGeometry.h>
#include <PartDefinition/IPlaneSurface.h>
#include <PartDefinition/IPlateGeometry.h>
#include <PartDefinition/IScanPlan.h>
#include <PartDefinition/ISpecimen.h>
#include <PartDefinition/ITubularGeometry.h>
#include <PartDefinition/IWeld.h>
#include <PartDefinition/IWeldedSpecimen.h>
#include <PartDefinition/IWeldFillCollection.h>
#include <PartDefinition/IWeldLandOfCrossPenetration.h>
#include <PartDefinition/IWeldSection.h>
#include <PartDefinition/IWeldCap.h>
